### ISSUE TITLE
WHY THIS FRAMEWORK WAS MADE?

### ISSUE THREAD

**Issue by gnanakeethan** [rawphp-framework/rawphp#2]
IS THERE ANY 1 USEFUL THING IN THIS FRAMEWORK. ALL IDIOTIC CODE.

**Comment by gnanakeethan** [comment]
You can make money by doing something else. not ruining people's time.

**Comment by davepartner** [comment]
Thanks @gnanakeethan, you asked a very important question. 

As started in the readme.  
It was made to help people from different PHP framework backgrounds work on the same project seamlessly.
A laravel and a CakePHP guy and a ZEND guy can work on the same project, same controller same view without needing to learn other people's code.
If you have worked in a large programming company, you will know that this is a real problem. 
It is also super easy to decouple, if you want to use blade template instead of twig for instance, you can install blade within seconds.

If a new PHP framework appears tomorrow, you just need to include it in your model and you are good to go.
